'use client'

import { useState } from 'react'
import { Lightbulb, X, Loader2, Sparkles } from 'lucide-react'

interface AIInsightsPanelProps {
  calculatorId: string
  calculatorName: string
  results: Record<string, number | string>
  userInput?: Record<string, number | string>
  location?: string
  role?: string
}

export default function AIInsightsPanel({
  calculatorId,
  calculatorName,
  results,
  userInput,
  location,
  role,
}: AIInsightsPanelProps) {
  const [isOpen, setIsOpen] = useState(false)
  const [insights, setInsights] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const fetchInsights = async () => {
    setLoading(true)
    setError(null)
    setInsights(null)
    setIsOpen(true)

    try {
      const response = await fetch('/api/insights', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          calculatorId,
          calculatorName,
          results,
          userInput,
          location,
          role,
        }),
      })

      if (!response.ok) {
        throw new Error('Failed to fetch insights')
      }

      const data = await response.json()
      setInsights(data.insights)
    } catch (err) {
      setError('Unable to generate insights. Please try again.')
      console.error('Insights error:', err)
    } finally {
      setLoading(false)
    }
  }

  return (
    <>
      {/* Button */}
      <button
        onClick={fetchInsights}
        disabled={loading}
        className="btn-secondary flex items-center gap-2 bg-gradient-to-r from-purple-600 to-blue-600 text-white hover:from-purple-700 hover:to-blue-700 disabled:opacity-50"
      >
        {loading ? (
          <Loader2 className="w-5 h-5 animate-spin" />
        ) : (
          <Sparkles className="w-5 h-5" />
        )}
        <span>AI Smart Insights</span>
      </button>

      {/* Panel */}
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50">
          <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-2xl max-w-lg w-full overflow-hidden">
            {/* Header */}
            <div className="flex items-center justify-between p-4 bg-gradient-to-r from-purple-600 to-blue-600 text-white">
              <div className="flex items-center gap-2">
                <Lightbulb className="w-6 h-6" />
                <h3 className="text-lg font-semibold">AI Smart Insights</h3>
              </div>
              <button
                onClick={() => setIsOpen(false)}
                className="p-1 hover:bg-white/20 rounded-full transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Content */}
            <div className="p-6">
              {loading && (
                <div className="flex flex-col items-center py-8">
                  <Loader2 className="w-10 h-10 text-purple-600 animate-spin mb-4" />
                  <p className="text-gray-600 dark:text-gray-300">Analyzing your results...</p>
                </div>
              )}

              {error && (
                <div className="bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 rounded-lg p-4">
                  {error}
                </div>
              )}

              {insights && (
                <div className="space-y-4">
                  <div className="bg-gradient-to-br from-purple-50 to-blue-50 dark:from-purple-900/20 dark:to-blue-900/20 rounded-lg p-4">
                    <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
                      {insights}
                    </p>
                  </div>
                  <p className="text-xs text-gray-500 dark:text-gray-400 text-center">
                    Generated by AI. For personalized advice, consult a financial professional.
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </>
  )
}
